[
	{
		"host": "db-ziotqhgnrvajjavhmenl",
		"component": "api",
		"_SYSTEMD_CGROUP": null,
		"request_id": "917ffe3db1c60704-CPT",
		"mail_from": null,
		"message": null,
		"_SOURCE_REALTIME_TIMESTAMP": null,
		"PRIORITY": null,
		"_AUDIT_LOGINUID": null,
		"panic": null,
		"metering": null,
		"UNIT": null,
		"event": null,
		"SYSLOG_FACILITY": null,
		"msg": "500: Database error saving new user",
		"mail_type": null,
		"EXECUTABLE": null,
		"user_id": null,
		"_CMDLINE": null,
		"action": null,
		"auth_event": [],
		"level": "error",
		"_PID": null,
		"path": "/signup",
		"duration": null,
		"_COMM": null,
		"header": null,
		"_MACHINE_ID": null,
		"login_method": null,
		"_STREAM_ID": null,
		"source_type": null,
		"_LINE_BREAK": null,
		"_EXE": null,
		"_AUDIT_SESSION": null,
		"_TRANSPORT": null,
		"x_forwarded_proto": null,
		"time": null,
		"mail_to": null,
		"_GID": null,
		"stack": null,
		"x_forwarded_host": null,
		"status": null,
		"_UID": null,
		"method": "POST",
		"CODE_FILE": null,
		"remote_addr": "104.28.196.149",
		"provider": null,
		"_SYSTEMD_UNIT": null,
		"issuer": null,
		"error": "failed to close prepared statement: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02): ERROR: column \"email\" of relation \"user\" does not exist (SQLSTATE 42703)",
		"client_id": null,
		"MESSAGE_ID": null,
		"referer": "http://localhost:3000/",
		"_SYSTEMD_INVOCATION_ID": null,
		"CODE_FUNC": null,
		"_BOOT_ID": null,
		"INVOCATION_ID": null,
		"__MONOTONIC_TIMESTAMP": null,
		"timestamp": null,
		"__REALTIME_TIMESTAMP": null,
		"CODE_LINE": null,
		"_SYSTEMD_SLICE": null,
		"instance_id": null,
		"args": [],
		"SYSLOG_IDENTIFIER": null,
		"metadata": [],
		"_CAP_EFFECTIVE": null,
		"factor_id": null,
		"_SELINUX_CONTEXT": null,
		"project": null
	}
]
